### ISSUE TITLE
Is there a reason this only publishes to the `dlltracer_dev` label?

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/dlltracer-feedstock#15]
### Comment:

It took me a while to figure out why I couldn't install it! 😅 

https://github.com/conda-forge/dlltracer-feedstock/blob/ed9a8472e37b48246e58e41e267d6feff2938749/recipe/conda_build_config.yaml#L1-L2

**Comment by traversaro** [comment]
Indeed, I had the same problem today (and ended up installing it via pip).

fyi @conda-forge/dlltracer @giotherobot

**Comment by traversaro** [comment]
By looking at https://github.com/conda-forge/staged-recipes/pull/15482#issuecomment-873168016 it seems that it was done as initially the tool only had an alpha release. However, I think that this can be removed since https://github.com/conda-forge/dlltracer-feedstock/pull/7 the releases are not an alpha.
